/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,json}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#d4af37',
        'on-primary': '#ffffff',
        'primary-container': '#fbf4dd',
        'on-primary-container': '#241a00',
        secondary: '#5f5e5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e2e1',
        'on-secondary-container': '#1c1b1b',
        tertiary: '#5d5f5f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e2e2e2',
        'on-tertiary-container': '#1a1c1c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#410002',
        background: '#ffffff',
        'on-background': '#1c1b1b',
        surface: '#ffffff',
        'on-surface': '#1c1b1b',
        'surface-variant': '#e7e2d3',
        'on-surface-variant': '#49473a',
        outline: '#7a7768',
        'outline-variant': '#cbc7b8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3e8',
        'surface-container': '#f1ede2',
        'surface-container-high': '#ebe7dc',
        'surface-container-highest': '#e5e2d6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      fontFamily: {
        'title-md': ['Playfair Display', 'serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        caption: ['Work Sans', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'label-md': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'display-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '0.1em', fontWeight: '600' },
        ],
      },
      spacing: {
        unit: '8px',
        'element-gap': '16px',
        'section-margin': '48px',
        gutter: '16px',
        'container-padding': '24px',
      },
    },
  },
  plugins: [],
};
